version: '3.9'

services:

  app:
    container_name: fastapi_container
    build:
      context: .
    env_file:
      - .env-docker
    ports:
      - '8000:8000'
    depends_on:
      - db

  db:
    container_name: postgres_container
    image: postgres
    env_file:
      - .env-docker
    ports:
      - '5432:5432'
    restart: always


